/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "adder.v:2.1-11.21" *)
module full_add(a, b, cin, sum, cout);
  (* src = "adder.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "adder.v:3.11-3.12" *)
  input b;
  wire b;
  (* src = "adder.v:3.13-3.16" *)
  input cin;
  wire cin;
  (* src = "adder.v:4.14-4.18" *)
  output cout;
  wire cout;
  (* src = "adder.v:4.10-4.13" *)
  output sum;
  wire sum;
  (* src = "adder.v:5.8-5.9" *)
  wire x;
  (* src = "adder.v:5.10-5.11" *)
  wire y;
  (* src = "adder.v:5.12-5.13" *)
  wire z;
  assign cout = z | y;
  (* module_not_derived = 32'd1 *)
  (* src = "adder.v:8.12-8.39" *)
  half_add h1 (
    .a(a),
    .b(b),
    .c(y),
    .s(x)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.v:9.12-9.43" *)
  half_add h2 (
    .a(x),
    .b(cin),
    .c(z),
    .s(sum)
  );
endmodule

(* src = "adder.v:14.1-21.20" *)
module half_add(a, b, s, c);
  (* src = "adder.v:15.9-15.10" *)
  input a;
  wire a;
  (* src = "adder.v:15.11-15.12" *)
  input b;
  wire b;
  (* src = "adder.v:16.12-16.13" *)
  output c;
  wire c;
  (* src = "adder.v:16.10-16.11" *)
  output s;
  wire s;
  assign s = b ^ a;
  assign c = b & a;
endmodule
